USE userSystemDb

CREATE TABLE Project (
    Id NVARCHAR(50) NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Security INT NOT NULL
);

CREATE TABLE [User] (
    Id NVARCHAR(50) NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(20) NULL,
    ProjectId NVARCHAR(50) NOT NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    Active BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_User_Project FOREIGN KEY (ProjectId) REFERENCES Project(Id)
);

CREATE TABLE Person (
    Id NVARCHAR(50) NOT NULL PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL,
    LastName NVARCHAR(255) NOT NULL,
    UserId NVARCHAR(50) NOT NULL,
    CONSTRAINT FK_Person_User FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE
);

ALTER TABLE Person
ADD PermissionLevel INT NOT NULL DEFAULT 1;

